###############-VERSION-###################
version: '3.7'

################-SERVICIOS-################

services:

###################-CLIENTE-#########################   
  client:
    container_name: cliente-http
    build: ./Client
    depends_on:
      - grpc_server
      - redis1
      - redis2
      - redis3
    ports:
      - "3000:3000"

###################-SERVIDOR-#########################  
  grpc_server:
    container_name: servidor-grpc
    build: ./ServerJS
    depends_on:
      - postgres
    ports:
      - "8030:8030"

#################-POSTGRES-##########################
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./Database/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"

###################-REDIS_SHARPS-##########################
  redis1:
    container_name: redis1
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis1",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lru"
      ]

  redis2:
    container_name: redis2
    image: redis:6.2.6
    restart: always
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis2",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu"
      ]
  
  redis3:
    container_name: redis3
    image: redis:6.2.6
    restart: always
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis3",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-random"
      ]
    
